{
procedure TForm10.DBEdit1KeyPress(Sender: TObject; var Key: Char );
begin
   if Key = chr(13) then if dbEdit2.Visible = True then dbEdit2.SetFocus else Button3.SetFocus;
   if Key = chr(46) then key := chr(44);
end;

procedure TForm10.DBEdit2KeyPress(Sender: TObject; var Key: Char);
begin

  if Key = chr(13) then if dbEdit3.Visible = True then dbEdit3.SetFocus else Button3.SetFocus;
  if Key = chr(46) then key := chr(44);

end;

procedure TForm10.DBEdit3KeyPress(Sender: TObject; var Key: Char);
begin
  if Key = chr(13) then if dbEdit4.Visible = True then dbEdit4.SetFocus else Button3.SetFocus;
  if Key = chr(46) then key := chr(44);
end;

procedure TForm10.DBEdit4KeyPress(Sender: TObject; var Key: Char);
begin
  if Key = chr(13) then if dbEdit5.Visible = True then dbEdit5.SetFocus else Button3.SetFocus;
  if Key = chr(46) then key := chr(44);
end;

procedure TForm10.DBEdit5KeyPress(Sender: TObject; var Key: Char);
begin
  if Key = chr(13) then if dbEdit6.Visible = True then dbEdit6.SetFocus else Button3.SetFocus;
  if Key = chr(46) then key := chr(44);
end;

procedure TForm10.DBEdit6KeyPress(Sender: TObject; var Key: Char);
begin
  if Key = chr(13) then if dbEdit7.Visible = True then dbEdit7.SetFocus else Button3.SetFocus;
  if Key = chr(46) then key := chr(44);
end;

procedure TForm10.DBEdit7KeyPress(Sender: TObject; var Key: Char);
begin
  if Key = chr(13) then if dbEdit8.Visible = True then dbEdit8.SetFocus else Button3.SetFocus;
  if Key = chr(46) then key := chr(44);
end;

procedure TForm10.DBEdit8KeyPress(Sender: TObject; var Key: Char);
begin
  if Key = chr(13) then if dbEdit9.Visible = True then dbEdit9.SetFocus else Button3.SetFocus;
  if Key = chr(46) then key := chr(44);
end;

procedure TForm10.DBEdit9KeyPress(Sender: TObject; var Key: Char);
begin
  if Key = chr(13) then if dbEdit10.Visible = True then dbEdit10.SetFocus else Button3.SetFocus;
  if Key = chr(46) then key := chr(44);
end;

procedure TForm10.DBEdit10KeyPress(Sender: TObject; var Key: Char);
begin
  if Key = chr(13) then if dbEdit11.Visible = True then dbEdit11.SetFocus else Button3.SetFocus;
  if Key = chr(46) then key := chr(44);
end;

procedure TForm10.DBEdit11KeyPress(Sender: TObject; var Key: Char);
begin
  if Key = chr(13) then if dbEdit12.Visible = True then dbEdit12.SetFocus else Button3.SetFocus;
  if Key = chr(46) then key := chr(44);
end;

procedure TForm10.DBEdit12KeyPress(Sender: TObject; var Key: Char);
begin
  if Key = chr(13) then if dbEdit13.Visible = True then dbEdit13.SetFocus else Button3.SetFocus;
  if Key = chr(46) then key := chr(44);
end;

procedure TForm10.DBEdit13KeyPress(Sender: TObject; var Key: Char);
begin
  if Key = chr(13) then if dbEdit14.Visible = True then dbEdit14.SetFocus else Button3.SetFocus;
  if Key = chr(46) then key := chr(44);
end;

procedure TForm10.DBEdit14KeyPress(Sender: TObject; var Key: Char);
begin
  if Key = chr(13) then if dbEdit15.Visible = True then dbEdit15.SetFocus else Button3.SetFocus;
  if Key = chr(46) then key := chr(44);
end;

procedure TForm10.DBEdit15KeyPress(Sender: TObject; var Key: Char);
begin
  if Key = chr(13) then if dbEdit16.Visible = True then dbEdit16.SetFocus else Button3.SetFocus;
  if Key = chr(46) then key := chr(44);
end;

procedure TForm10.DBEdit16KeyPress(Sender: TObject; var Key: Char);
begin
  if Key = chr(13) then if dbEdit17.Visible = True then dbEdit17.SetFocus else Button3.SetFocus;
  if Key = chr(46) then key := chr(44);
end;

procedure TForm10.DBEdit17KeyPress(Sender: TObject; var Key: Char);
begin
  if Key = chr(13) then if dbEdit18.Visible = True then dbEdit18.SetFocus else Button3.SetFocus;
  if Key = chr(46) then key := chr(44);
end;

procedure TForm10.DBEdit18KeyPress(Sender: TObject; var Key: Char);
begin
  if Key = chr(13) then if dbEdit19.Visible = True then dbEdit19.SetFocus else Button3.SetFocus;
  if Key = chr(46) then key := chr(44);
end;

procedure TForm10.DBEdit19KeyPress(Sender: TObject; var Key: Char);
begin
  if Key = chr(13) then Button3.SetFocus;
  if Key = chr(46) then key := chr(44);
end;
}