unit nfse.classes.servico.exigibilidadeiss;

interface

type
  TExigibilidadeIss = type Integer;

const
  EXIGIBILIDADE_ISS_EXIGIVEL = 0;
  EXIGIBILIDADE_ISS_NAOINCIDENCIA = 1;
  EXIGIBILIDADE_ISS_ISENCAO = 2;
  EXIGIBILIDADE_ISS_EXPORTACAO = 3;
  EXIGIBILIDADE_ISS_IMUNIDADE = 4;
  EXIGIBILIDADE_ISS_SUSPENSAO_JUDICIAL = 5;
  EXIGIBILIDADE_ISS_SUSPENSA_PROCESSO_ADMINISTRATIVO = 6;
  EXIGIBILIDADE_ISS_FIXO = 7;

implementation

end.

